/* Stack Rush service worker — generated by build_mobile.py */
const CACHE = 'stackrush-c0c7ca35';
const ASSETS = [
  "./index.html",
  "./manifest.webmanifest",
  "./icon.svg",
  "./icon-192.png",
  "./icon-512.png",
  "./assets/drop.wav",
  "./assets/land.wav",
  "./assets/perfect.wav",
  "./assets/great.wav",
  "./assets/good.wav",
  "./assets/slice.wav",
  "./assets/gameover.wav",
  "./assets/slide.wav",
  "./assets/music_neon.wav",
  "./assets/music_chiptune.wav",
  "./assets/music_lofi.wav",
  "./assets/music_synth.wav",
  "./assets/music_dream.wav",
  "./assets/cities/neon.png",
  "./assets/cities/nyc.png",
  "./assets/cities/toronto.png",
  "./assets/cities/tokyo.png"
];

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin) return;
  e.respondWith(
    caches.match(e.request).then((hit) => hit || fetch(e.request).then((res) => {
      if (!res || res.status !== 200) return res;
      const copy = res.clone();
      caches.open(CACHE).then((c) => c.put(e.request, copy));
      return res;
    })).catch(() => caches.match('./index.html')))
  );
});
